- name: Operating System
  debug:
    msg: '{{ ansible_distribution }} {{ ansible_distribution_release }} as: {{ distro[ansible_distribution] }} {{ distro_release }}'

- name: Remove incompatible packages
  become: yes
  apt:
    name: '{{ docker_incompatibility_packages }}'
    state: absent

- name: Install apt dependencies
  become: yes
  apt:
    name: '{{ docker_apt_dependencies }}'
    update_cache: yes
    state: present

- name: Add apt-key
  become: yes
  apt_key:
    url: '{{ docker_gpgkey_url }}'
    id: '{{ docker_gpgkey_fingerprint }}'
    state: present

- name: Add repository
  become: yes
  apt_repository:
    repo: '{{ docker_apt_repo }}'
    state: present
    mode: '0644'

- name: Install
  become: yes
  apt:
    name: '{{ docker_apt }}'
    state: present
  notify: Restart Docker

- name: Run at boot
  become: yes
  service:
    name: docker
    state: started
    enabled: true

- name: Check if in group
  shell: |
    set -o pipefail
    id -nG | grep docker
  args:
    executable: /bin/bash
  changed_when: false
  register: in_docker_group
  failed_when: in_docker_group.rc > 1

- name: Add user to Docker group
  become: yes
  command: 'usermod -aG docker {{ ansible_user }}'
  when: in_docker_group.rc != 0
  notify: Docker user added
