---
- name: Restart Docker
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Docker user added
  ansible.builtin.debug:
    msg: "A new user has been added to the Docker group. Please log out and log back in for this change to apply to the user."
