---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:

  - name: Get executable
    stat:
      path: /usr/bin/docker
    register: docker_exec

  - name: Assertions
    assert:
      that:
        - docker_exec.stat.exists
