---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:

  - name: Hello World
    command: docker run hello-world
    register: hello_world
    failed_when: false
    changed_when: false

  - name: Assertions
    assert:
      that:
        - hello_world.rc == 0
