name: Ansible

on:
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distros:
          - geerlingguy/docker-ubuntu2004-ansible:latest
          - geerlingguy/docker-ubuntu1804-ansible:latest
          - geerlingguy/docker-ubuntu1604-ansible:latest
          - ghcr.io/artis3n/docker-ubuntu2010-ansible:latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set Up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Move project to Ansible-required location
        run: |
          mkdir -p ~/.ansible/roles/artis3n.docker
          cp -r ./ ~/.ansible/roles/artis3n.docker

      - name: Test
        run: pipenv run molecule test
        env:
          MOLECULE_DISTRO: "${{ matrix.distros }}"
