name: Ansible

on:
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distros:
          - geerlingguy/docker-ubuntu2004-ansible:latest
          - geerlingguy/docker-ubuntu1804-ansible:latest
          - geerlingguy/docker-ubuntu1604-ansible:latest
          - ghcr.io/artis3n/docker-ubuntu2104-ansible:latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set Up Python 3
        id: setup-python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.10'

      - uses: actions/cache@v2.1.7
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Test
        run: pipenv run molecule test
        env:
          MOLECULE_DISTRO: "${{ matrix.distros }}"
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
