name: Ansible

on:
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        distros:
          - geerlingguy/docker-ubuntu2204-ansible:latest
          - geerlingguy/docker-ubuntu2004-ansible:latest
          - geerlingguy/docker-ubuntu1804-ansible:latest
          - geerlingguy/docker-ubuntu1604-ansible:latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      # - name: Install package manager
      #   run: pipx install poetry

      - name: Set Up Python 3
        id: setup-python
        uses: actions/setup-python@v4.4.0
        with:
          python-version: '3.10'
          # cache: 'poetry'

      - name: Install dependency manager
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Test
        run: poetry run molecule test
        env:
          MOLECULE_DISTRO: "${{ matrix.distros }}"
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
