name: Ansible

on:
  pull_request:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Move project to Ansible-required location
        run: |
          mkdir -p ~/.ansible/roles/artis3n.docker
          cp -r ./ ~/.ansible/roles/artis3n.docker

      - name: Test
        run: pipenv run molecule test --skip-tags sockets
